/**
 * 若依后端菜单 `icon` 常为 Element / 旧版命名（如 system-o），与 ng-zorro `nzType` 不兼容。
 * 映射到已在 style-icons-auto 中注册的 Ant Design 图标名；未知则回退，避免 IconNotFoundError。
 */
const SAFE_NZ_TYPES = new Set([
  'alipay-circle',
  'arrow-down',
  'arrow-left',
  'block',
  'caret-right',
  'code',
  'copyright',
  'dashboard',
  'delete',
  'down',
  'download',
  'edit',
  'expand',
  'export',
  'compress',
  'eye',
  'file-text',
  'fullscreen-exit',
  'fullscreen',
  'github',
  'global',
  'import',
  'key',
  'lock',
  'logout',
  'mail',
  'mobile',
  'more',
  'plus',
  'reload',
  'safety',
  'search',
  'setting',
  'sync',
  'taobao-circle',
  'team',
  'tool',
  'upload',
  'user',
  'weibo-circle'
]);

/** 若依 / Element 常用图标名 → 安全 nzType */
const RUOYI_ICON_MAP: Record<string, string> = {
  system: 'setting',
  'system-o': 'setting',
  monitor: 'eye',
  'monitor-o': 'eye',
  guide: 'file-text',
  'guide-o': 'file-text',
  tool: 'tool',
  peoples: 'team',
  tree: 'block',
  dict: 'file-text',
  logininfor: 'key',
  online: 'global',
  job: 'sync',
  druid: 'eye',
  server: 'block',
  redis: 'block',
  swagger: 'code',
  build: 'tool',
  code: 'code',
  message: 'mail',
  documentation: 'file-text',
  dashboard: 'dashboard',
  user: 'user',
  lock: 'lock',
  list: 'file-text',
  chart: 'dashboard',
  component: 'block',
  email: 'mail',
  link: 'code',
  log: 'file-text',
  nested: 'block',
  search: 'search',
  shopping: 'tool',
  star: 'safety',
  tab: 'block',
  table: 'file-text',
  theme: 'setting',
  zip: 'download',
  bug: 'block',
  upload: 'upload',
  form: 'file-text',
  edit: 'edit',
  icon: 'block',
  international: 'global',
  language: 'global',
  clipboard: 'file-text',
  example: 'file-text',
  excel: 'export',
  number: 'file-text',
  pdf: 'file-text',
  people: 'team',
  qq: 'user',
  size: 'block',
  skill: 'tool',
  tree_table: 'block',
  wechat: 'user',
  color: 'block',
  drag: 'block',
  icons: 'block',
  json: 'code',
  textarea: 'file-text',
  valid_code: 'safety',
  button: 'block',
  education: 'file-text',
  row: 'block',
  time: 'file-text',
  time_range: 'file-text',
  password: 'lock',
  post: 'file-text',
  radio: 'block',
  select: 'block',
  checkbox: 'block',
  input: 'file-text',
  slider: 'block',
  switch: 'block',
  transfer: 'export',
  calendar: 'file-text',
  mention: 'mail',
  tree_select: 'block',
  watermark: 'block',
  anchor: 'block',
  breadcrumb: 'block',
  dropdown: 'down',
  page_header: 'file-text',
  pagination: 'file-text',
  steps: 'block',
  alert: 'safety',
  drawer: 'block',
  loading: 'reload',
  notification: 'mail',
  popconfirm: 'safety',
  popover: 'file-text',
  result: 'file-text',
  skeleton: 'block',
  spin: 'reload',
  affix: 'block',
  divider: 'block',
  layout: 'block',
  space: 'block',
  statistic: 'dashboard',
  tag: 'block',
  check: 'safety',
  close: 'delete',
  info: 'safety',
  success: 'safety',
  warning: 'safety',
  error: 'delete',
  question: 'safety',
  smile: 'user',
  heart: 'safety',
  like: 'safety',
  dislike: 'delete',
  robot: 'user',
  cloud: 'global',
  fire: 'safety',
  thunderbolt: 'safety',
  experiment: 'tool',
  apartment: 'team',
  tablet: 'mobile',
  laptop: 'block',
  desktop: 'block',
  database: 'block',
  api: 'code',
  fork: 'code',
  branches: 'code',
  merge: 'code',
  pull_request: 'code',
  github: 'github',
  gitlab: 'github',
  dingding: 'mail',
  alipay: 'alipay-circle',
  taobao: 'taobao-circle',
  weibo: 'weibo-circle',
  html5: 'code',
  css3: 'code',
  apple: 'block',
  android: 'mobile',
  windows: 'block',
  ie: 'block',
  chrome: 'block',
  safari: 'block',
  firefox: 'block',
  opera: 'block',
  edge: 'block',
  medium: 'file-text',
  sketch: 'tool',
  dribbble: 'block',
  behance: 'block',
  ant_design: 'block',
  ant_cloud: 'global',
  aliwangwang: 'mail',
  yuque: 'file-text',
  zhihu: 'file-text',
  slack: 'team',
  yahoo: 'mail',
  reddit: 'block',
  twitter: 'global',
  whatsapp: 'global',
  linkedin: 'team',
  facebook: 'team',
  instagram: 'global',
  google: 'global',
  google_plus: 'global',
  skype: 'user',
  dingtalk: 'mail'
};

const FALLBACK_NZ_TYPE = 'block';

function normalizeIconKey(raw: string): string {
  let s = raw.trim().toLowerCase();
  if (s.startsWith('el-icon-')) s = s.slice('el-icon-'.length);
  if (s.startsWith('#')) s = s.slice(1);
  return s.replace(/\s+/g, '');
}

function pickSafe(mapped: string | undefined): string {
  if (mapped && SAFE_NZ_TYPES.has(mapped)) return mapped;
  return FALLBACK_NZ_TYPE;
}

/**
 * 将若依菜单图标字段转为可用的 nz-icon nzType；无法识别时返回安全默认值。
 */
export function menuIconToNzType(raw: string | undefined | null): string {
  if (raw == null || raw === '') return FALLBACK_NZ_TYPE;
  const key = normalizeIconKey(raw);
  if (!key) return FALLBACK_NZ_TYPE;
  if (RUOYI_ICON_MAP[key]) return pickSafe(RUOYI_ICON_MAP[key]);
  if (key.endsWith('-o')) {
    const base = key.slice(0, -2);
    if (RUOYI_ICON_MAP[base]) return pickSafe(RUOYI_ICON_MAP[base]);
    if (RUOYI_ICON_MAP[key]) return pickSafe(RUOYI_ICON_MAP[key]);
  }
  if (SAFE_NZ_TYPES.has(key)) return key;
  return FALLBACK_NZ_TYPE;
}
